### ISSUE TITLE
V 1.1.0 fails to update to 1.2.0

### ISSUE THREAD

**Issue by apoapostolov** [Utkarsh-G/heroic-variant#1]
The json seems to repeat v.1.1.0, it enters a loop

**Comment by Antorrion** [comment]
Same problem

**Comment by Utkarsh-G** [comment]
Thanks for reporting! I think I have a fix in place now. Just need to update the foundry links, and then test out the upgrade path.

**Comment by Utkarsh-G** [comment]
Foundry has been updated. Testing now.

**Comment by Utkarsh-G** [comment]
Looking good so far, so I'm closing this issue.
